### PR TITLE
[rotors] bugfixes for rotors sim and frontend changes

### LINKED ISSUE #181: [rotors] bugfixes and frontend changes
PR #180

### PR DESCRIPTION
**Pull request by RUFFY-369**
Bugfixes and frontend changes

### CODE REVIEW

**Comment by RUFFY-369** [comment]
@pariaspe  , @iamarkaj

**Review by pariaspe — COMMENTED** [review]
Some comments:
- Why changing car beacon on visual landing exercise?
- Is it possible to change QRs with aruco markers in the packages?
- Aruco vs apriltag?
- Aruco on turtlebot?

PS: Review of python files is still missing..

**Comment by RUFFY-369** [comment]
- Not a strategic choice but just thought that the drone will look good landing on moving landing pad
- It's possible to change by changing the texture file of QR to Aruco. But right now the QRs are used for getting the coordinates of the target in package_delivery and Aruco is used for localisation or landmarking. I don't know if changing QR to Aruco will be beneficial for getting coordinates. And QR basically just simulates how it's done in real life with drone package delivery.
- Not much of a difference as both are used in landmarking system but Apriltag works well for long range detection i.e., more height of the drone
- It can be done by changing the texture file but again both performs same role but Apriltag  works well for long range

**Comment by pariaspe** [comment]
Hi @RUFFY-369 , sorry for the late response

> * Not a strategic choice but just thought that the drone will look good landing on moving landing pad

Not sure about this, the previous one is easier to detect, even when you are close to the car.

> * It's possible to change by changing the texture file of QR to Aruco. But right now the QRs are used for getting the coordinates of the target in package_delivery and Aruco is used for localisation or landmarking. I don't know if changing QR to Aruco will be beneficial for getting coordinates. And QR basically just simulates how it's done in real life with drone package delivery.

The good thing about Aruco markers is that they are included in opencv. How are you planning to read QRs?

> * Not much of a difference as both are used in landmarking system but Apriltag works well for long range detection i.e., more height of the drone

As I said above, I normally use/prefer Aruco due to its opencv integration.

> * It can be done by changing the texture file but again both performs same role but Apriltag  works well for long range

Same.

**Comment by pariaspe** [comment]
pr split up in #183, #184, #185

**Pull request closed without merging**
