### PR TITLE
Add installation20.md

### PR DESCRIPTION
**Pull request by RUFFY-369**
Added the installation20.md for ROS Noetic Ubuntu 20.04 (issue #80 )

### CODE REVIEW

**Comment by pariaspe** [comment]
Hi @RUFFY-369,
Have you installed all the software? I've not checked the full installation process, since I'm still using a Ubuntu18.04 machine. However, I've been checking the installing instructions of all the dependencies and PX4 might required Gazebo9 as you can check in their installation [script](https://github.com/PX4/PX4-Autopilot/blob/v1.11.0/Tools/setup/ubuntu.sh).

**Comment by iamarkaj** [comment]
> Hi @RUFFY-369,
> Have you installed all the software? I've not checked the full installation process, since I'm still using a Ubuntu18.04 machine. However, I've been checking the installing instructions of all the dependencies and PX4 might required Gazebo9 as you can check in their installation [script](https://github.com/PX4/PX4-Autopilot/blob/v1.11.0/Tools/setup/ubuntu.sh).

Checkout the new installation [script](https://github.com/PX4/PX4-Autopilot/blob/master/Tools/setup/ubuntu.sh)

**Comment by iamarkaj** [comment]
You can checkout this file. [This](https://gist.github.com/iamarkaj/45ceb4b87081ef5e2797a380dd0d9866) is the list of instructions very naively written.

versions

https://user-images.githubusercontent.com/40225765/116339387-f5a7a780-a7fa-11eb-9fb9-583e541fc3f5.mp4

**Comment by pariaspe** [comment]
Thanks @iamarkaj, your gist is great! Just a little remark, we should aim to use a tagged version, since master branch may be unstable.

I'm merging @RUFFY-369's PR, but many changes are required. This doc should only contain required dependencies, so some of the current dependencies have to be deleted.

**Review by pariaspe — APPROVED** [review]

**Pull request merged**
