### PR TITLE
[melodic] Added meshes of all iris models

### PR DESCRIPTION
**Pull request by iamarkaj**
Closes issue #105

### CODE REVIEW

**Comment by pariaspe** [comment]
Drone models were working in Melodic distribution using meshes from PX4/sitl-gazebo package.
However, including the meshes to drone_assets will do it more self-contained. Good proposal.

Please, push these changes to melodic-devel branch too.

**Comment by iamarkaj** [comment]
Isn't the master branch for melodic specifically? What is the role of melodic-devel branch?

**Comment by pariaspe** [comment]
> Isn't the master branch for melodic specifically? What is the role of melodic-devel branch?

It was at the past. Currently, the upstream branch is melodic-devel. 
During the time where only one distribution was matained, I kept master branch up-to-date too.

**Comment by pariaspe** [comment]
Closing, meshes are not strictly needed

**Pull request closed without merging**
